version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./db:/data # Mount the volume to persist the data
      - ./app:/app # Mount the app directory to the container
    command: python manage.py runserver 0.0.0.0:8000
